openapi: 3.0.3
servers:
  - url: http://localhost:3000
info:
  title: Module 295 Book Library API System
  description: |
    A service which stores all required data for books, customers and what those customers have lend.
  contact:
    name: Manassés Zähnler
    email: manasses.zaehnler@outlook.com
  version: 1.0.0

tags:
  - name: books
  - name: lends

paths:
  '/books':
    get:
      tags:
        - books
      summary: Read all books
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/book'
        '500':
          description: Internal Server Error

    post: 
      tags:
        - books
      summary: Create a new book
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
      responses:  
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book' 
        '400':
          description: Bad Request
        '422':
          description: Unprocessable Content
        '500':
          description: Internal Server Error
    
  '/books/{isbn}':
    get:
      tags:
        - books
      summary: Read a single book by its isbn
      parameters:
        - $ref: '#/components/parameters/isbn'
      responses:
        '200':
          description: OK
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

    patch:
      tags: 
        - books
      summary: Update a book by its isbn
      parameters: 
        - $ref: '#/components/parameters/isbn'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        '404':
          description: Not Found
        '422':
          description: Unprocessable Content
        '500':
          description: Internal Server Error

    put:
      tags: 
        - books
      summary: Update a book by its isbn
      parameters: 
        - $ref: '#/components/parameters/isbn'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/book'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/book'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '422':
          description: Unprocessable Content
        '500':
          description: Internal Server Error

    delete:
      tags: 
        - books
      summary: Delete a book by its isbn
      parameters:
        - $ref: '#/components/parameters/isbn'
      responses:
        '204':
          description: No Content
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          
  '/lends':
    get:
      tags:
        - lends
      summary: Read all lends
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/lend'
        '500':
          description: Internal server error

  '/lends/{id}':
    get:
      tags:
        - lends
      summary: Read a single lend by its id
      parameters:
        - $ref: '#/components/parameters/id'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lend'
        '404': 
          description: Not Found
        '500':
          description: Internal Server Error
    
    post:
      tags:
        - lends
      summary: Create a new lend
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lend'
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lend'
        '400':
          description: Bad Request 
        '422': 
          description: Unprocessable Content
        '500':
          description: Internal Server Error          

    patch:
      tags:
        - lends
      summary: Update a single lend by its id.
      parameters:
        - $ref: '#/components/parameters/id'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/lend'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lend'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
          
  
components:
  parameters:
    isbn:
      name: isbn
      in: path
      required: true
      description: The isbn of a book
      schema:
        type: string
    
    id:
      name: id
      in: path
      required: true
      description: The id of a lend
      schema:
        type: string

  schemas:
    book:
      description: A book entry
      type: object
      properties:
        isbn:
          type: string
          example: "9780743273565"
        title: 
          type: string
          example: "The Great Gatsby"
        year:
          type: integer
          example: 1925
        author:
          type: string 
          example: "F. Scott Fitzgerald" 
    
    lend:
      description: A lend entry
      type: object
      properties:
        id:
          type: string
          example: "9ddf01d0-57df-4707-9879-fb7364dad07b"
        customer_id:
          type: integer
          format: int64
          example: 1433 
        isbn:
          type: string
          example: "9780743273565"
        borrowed_at:
          type: string
          format: date-time
          example: "2023-06-01T13:16:58.261Z"
        returned_at:
          type: string
          format: date-time
          example: "2023-06-05T12:35:52.261Z"
        

    